repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v2.3.0"
    hooks:
      - id: check-yaml
      - id: check-ast
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/lorenzwalthert/precommit
    rev: v0.4.3
    hooks:
      - id: lintr
        args: [--warn_only, --key=value]
